### Bank Loans  
This notebook is based on real (anonymous) data from a local bank in Palestine. There are 1000 data points available in this dataset (loans.csv file in the current folder). We are trying to get meta data for the dataset and also aadditional rows and hopefully some missing values but this is nt guaranteed.   
This notebook is by no means the best approach or most accurate model. It was meant to be a starter only.  
If you use this data and get exciting results, please share them.

In [2]:
import numpy as np
import pandas as pd

In [3]:
loans = pd.read_csv('loans.csv', header=0, sep = ',')
pd.options.display.max_columns = 100 # display all columns
loans.head(5)
#loans.describe()

,checking_balance,months_loan_duration,credit_history,purpose,amount,savings_balance,employment_length,installment_rate,personal_status,other_debtors,residence_history,property,age,installment_plan,housing,existing_credits,default,dependents,telephone,foreign_worker,job
0,< 0 DM,6,critical,radio/tv,1169,unknown,> 7 yrs,4,single male,none,4,real estate,67,none,own,2,1,1,yes,yes,skilled employee
1,1 - 200 DM,48,repaid,radio/tv,5951,< 100 DM,1 - 4 yrs,2,female,none,2,real estate,22,none,own,1,2,1,none,yes,skilled employee
2,unknown,12,critical,education,2096,< 100 DM,4 - 7 yrs,2,single male,none,3,real estate,49,none,own,1,1,2,none,yes,unskilled resident
3,< 0 DM,42,repaid,furniture,7882,< 100 DM,4 - 7 yrs,2,single male,guarantor,4,building society savings,45,none,for free,1,1,2,none,yes,skilled employee
4,< 0 DM,24,delayed,car (new),4870,< 100 DM,1 - 4 yrs,3,single male,none,4,unknown/none,53,none,for free,2,2,2,none,yes,skilled employee

In [4]:
#loans.columns[-1]
print("checking_balance:",loans['checking_balance'].unique())
print("savings_balance:",loans['savings_balance'].unique())
print("months_loan_duration:",loans['months_loan_duration'].unique()) # can be considered continuous
print("credit_history:",loans['credit_history'].unique()) # consolidate: critical, repaid, delayed [labels]
print("purpose:",loans['purpose'].unique())
print("employment_length:",loans['employment_length'].unique()) # encode as numbers from 0 (unemployed) to 4(>7 yrs)
print("installment_rate:",loans['installment_rate'].unique())
print("personal_status:",loans['personal_status'].unique()) # split into gender and personal status
# .... check the rest of the columns
print("jobs:",loans['job'].unique())

checking_balance: ['< 0 DM' '1 - 200 DM' 'unknown' '> 200 DM']
savings_balance: ['unknown' '< 100 DM' '501 - 1000 DM' '> 1000 DM' '101 - 500 DM']
months_loan_duration: [ 6 48 12 42 24 36 30 15  9 10  7 60 18 45 11 27  8 54 20 14 33 21 16  4 47
 13 22 39 28  5 26 72 40]
credit_history: ['critical' 'repaid' 'delayed' 'fully repaid' 'fully repaid this bank']
purpose: ['radio/tv' 'education' 'furniture' 'car (new)' 'car (used)' 'business'
 'domestic appliances' 'repairs' 'others' 'retraining']
employment_length: ['> 7 yrs' '1 - 4 yrs' '4 - 7 yrs' 'unemployed' '0 - 1 yrs']
installment_rate: [4 2 3 1]
personal_status: ['single male' 'female' 'divorced male' 'married male']
jobs: ['skilled employee' 'unskilled resident' 'mangement self-employed'
 'unemployed non-resident']

In [5]:
loans['checking_balance'].value_counts()

unknown       394
< 0 DM        274
1 - 200 DM    269
> 200 DM       63
Name: checking_balance, dtype: int64

In [6]:
loans['savings_balance'].value_counts()

< 100 DM         603
unknown          183
101 - 500 DM     103
501 - 1000 DM     63
> 1000 DM         48
Name: savings_balance, dtype: int64

In [7]:
loans['credit_history'].value_counts()

repaid                    530
critical                  293
delayed                    88
fully repaid this bank     49
fully repaid               40
Name: credit_history, dtype: int64

In [8]:
# parse the personal status into gender and status
# female, male or N(one)
# we already know the options from above, all lower case, so no further text processing
def getGender(txt):
    if "female" in txt:
        return "F"
    if "male" in txt:
        return "M"
    return "N"

# married, single, divorced or U(nknown)
def getStatus(txt):
    if "maried" in txt:
        return "M"
    if "single" in txt:
        return "S"
    if "divorced" in txt:
        return "D"    
    return "U"

def getHistory(txt):
    if "repaid" in txt:
        return "R"
    if "critical" in txt:
        return "C"  
    return "D"

In [9]:
loans["gender"] = loans["personal_status"].apply(getGender)
loans["pstatus"] = loans["personal_status"].apply(getStatus)
loans["history"] = loans["credit_history"].apply(getHistory)
loans["default"] = loans["default"] -1

In [10]:
loans.head(5)

,checking_balance,months_loan_duration,credit_history,purpose,amount,savings_balance,employment_length,installment_rate,personal_status,other_debtors,residence_history,property,age,installment_plan,housing,existing_credits,default,dependents,telephone,foreign_worker,job,gender,pstatus,history
0,< 0 DM,6,critical,radio/tv,1169,unknown,> 7 yrs,4,single male,none,4,real estate,67,none,own,2,0,1,yes,yes,skilled employee,M,S,C
1,1 - 200 DM,48,repaid,radio/tv,5951,< 100 DM,1 - 4 yrs,2,female,none,2,real estate,22,none,own,1,1,1,none,yes,skilled employee,F,U,R
2,unknown,12,critical,education,2096,< 100 DM,4 - 7 yrs,2,single male,none,3,real estate,49,none,own,1,0,2,none,yes,unskilled resident,M,S,C
3,< 0 DM,42,repaid,furniture,7882,< 100 DM,4 - 7 yrs,2,single male,guarantor,4,building society savings,45,none,for free,1,0,2,none,yes,skilled employee,M,S,R
4,< 0 DM,24,delayed,car (new),4870,< 100 DM,1 - 4 yrs,3,single male,none,4,unknown/none,53,none,for free,2,1,2,none,yes,skilled employee,M,S,D

In [11]:
# not sure about existing_credits
dummy_columns = ['gender','checking_balance','purpose','savings_balance','employment_length',
                 'installment_rate','other_debtors','residence_history', 'property','installment_plan',
                'housing','telephone','foreign_worker','job','pstatus', 'history']
new_loans = pd.get_dummies(loans, columns=dummy_columns, drop_first=True)
new_loans.head(5)

,months_loan_duration,credit_history,amount,personal_status,age,existing_credits,default,dependents,gender_M,checking_balance_< 0 DM,checking_balance_> 200 DM,checking_balance_unknown,purpose_car (new),purpose_car (used),purpose_domestic appliances,purpose_education,purpose_furniture,purpose_others,purpose_radio/tv,purpose_repairs,purpose_retraining,savings_balance_501 - 1000 DM,savings_balance_< 100 DM,savings_balance_> 1000 DM,savings_balance_unknown,employment_length_1 - 4 yrs,employment_length_4 - 7 yrs,employment_length_> 7 yrs,employment_length_unemployed,installment_rate_2,installment_rate_3,installment_rate_4,other_debtors_guarantor,other_debtors_none,residence_history_2,residence_history_3,residence_history_4,property_other,property_real estate,property_unknown/none,installment_plan_none,installment_plan_stores,housing_own,housing_rent,telephone_yes,foreign_worker_yes,job_skilled employee,job_unemployed non-resident,job_unskilled resident,pstatus_S,pstatus_U,history_D,history_R
0,6,critical,1169,single male,67,2,0,1,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,1,0,1,0,0,1,0,1,0,1,0,1,0,1,1,1,0,0,1,0,0,0
1,48,repaid,5951,female,22,1,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,0,1,0,0,0,1,1,0,0,0,1,0,1,0,1,0,0,1,1,0,0,0,1,0,1
2,12,critical,2096,single male,49,1,0,2,1,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,0,1,0,1,0,0,1,0,1,0,1,0,0,1,0,0,1,1,0,0,0
3,42,repaid,7882,single male,45,1,0,2,1,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,1,0,0,1,0,0,1
4,24,delayed,4870,single male,53,2,1,2,1,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,1,0,0,1,1,0,0,0,0,1,1,0,0,1,0,1,0

In [12]:
loans = new_loans.drop(['credit_history', 'personal_status'], axis=1)
loans.head(5)

,months_loan_duration,amount,age,existing_credits,default,dependents,gender_M,checking_balance_< 0 DM,checking_balance_> 200 DM,checking_balance_unknown,purpose_car (new),purpose_car (used),purpose_domestic appliances,purpose_education,purpose_furniture,purpose_others,purpose_radio/tv,purpose_repairs,purpose_retraining,savings_balance_501 - 1000 DM,savings_balance_< 100 DM,savings_balance_> 1000 DM,savings_balance_unknown,employment_length_1 - 4 yrs,employment_length_4 - 7 yrs,employment_length_> 7 yrs,employment_length_unemployed,installment_rate_2,installment_rate_3,installment_rate_4,other_debtors_guarantor,other_debtors_none,residence_history_2,residence_history_3,residence_history_4,property_other,property_real estate,property_unknown/none,installment_plan_none,installment_plan_stores,housing_own,housing_rent,telephone_yes,foreign_worker_yes,job_skilled employee,job_unemployed non-resident,job_unskilled resident,pstatus_S,pstatus_U,history_D,history_R
0,6,1169,67,2,0,1,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,1,0,1,0,0,1,0,1,0,1,0,1,0,1,1,1,0,0,1,0,0,0
1,48,5951,22,1,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,0,1,0,0,0,1,1,0,0,0,1,0,1,0,1,0,0,1,1,0,0,0,1,0,1
2,12,2096,49,1,0,2,1,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,0,1,0,1,0,0,1,0,1,0,1,0,0,1,0,0,1,1,0,0,0
3,42,7882,45,1,0,2,1,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,1,0,0,1,0,0,1
4,24,4870,53,2,1,2,1,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,1,0,0,1,1,0,0,0,0,1,1,0,0,1,0,1,0

In [13]:
loans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 51 columns):
months_loan_duration             1000 non-null int64
amount                           1000 non-null int64
age                              1000 non-null int64
existing_credits                 1000 non-null int64
default                          1000 non-null int64
dependents                       1000 non-null int64
gender_M                         1000 non-null uint8
checking_balance_< 0 DM          1000 non-null uint8
checking_balance_> 200 DM        1000 non-null uint8
checking_balance_unknown         1000 non-null uint8
purpose_car (new)                1000 non-null uint8
purpose_car (used)               1000 non-null uint8
purpose_domestic appliances      1000 non-null uint8
purpose_education                1000 non-null uint8
purpose_furniture                1000 non-null uint8
purpose_others                   1000 non-null uint8
purpose_radio/tv                 1000 non-null uint8
purpose_repairs                  1000 non-null uint8
purpose_retraining               1000 non-null uint8
savings_balance_501 - 1000 DM    1000 non-null uint8
savings_balance_< 100 DM         1000 non-null uint8
savings_balance_> 1000 DM        1000 non-null uint8
savings_balance_unknown          1000 non-null uint8
employment_length_1 - 4 yrs      1000 non-null uint8
employment_length_4 - 7 yrs      1000 non-null uint8
employment_length_> 7 yrs        1000 non-null uint8
employment_length_unemployed     1000 non-null uint8
installment_rate_2               1000 non-null uint8
installment_rate_3               1000 non-null uint8
installment_rate_4               1000 non-null uint8
other_debtors_guarantor          1000 non-null uint8
other_debtors_none               1000 non-null uint8
residence_history_2              1000 non-null uint8
residence_history_3              1000 non-null uint8
residence_history_4              1000 non-null uint8
property_other                   1000 non-null uint8
property_real estate             1000 non-null uint8
property_unknown/none            1000 non-null uint8
installment_plan_none            1000 non-null uint8
installment_plan_stores          1000 non-null uint8
housing_own                      1000 non-null uint8
housing_rent                     1000 non-null uint8
telephone_yes                    1000 non-null uint8
foreign_worker_yes               1000 non-null uint8
job_skilled employee             1000 non-null uint8
job_unemployed non-resident      1000 non-null uint8
job_unskilled resident           1000 non-null uint8
pstatus_S                        1000 non-null uint8
pstatus_U                        1000 non-null uint8
history_D                        1000 non-null uint8
history_R                        1000 non-null uint8
dtypes: int64(6), uint8(45)
memory usage: 90.9 KB

In [14]:
X = loans.drop('default',axis=1)
y = loans['default']
print(X.shape)
print(y.shape)

(1000, 50)
(1000,)

In [15]:
from sklearn.model_selection import train_test_split, cross_val_score, KFold, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC, SVC
from sklearn.metrics import accuracy_score, roc_auc_score, roc_curve, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [16]:
logreg = LogisticRegression(C=10, max_iter=200, n_jobs=3,solver='liblinear') 
# C=1, max_iter=100, solver='liblinear' 'newton-cg', 'lbfgs', 'liblinear', 'sag'
np.random.seed(79) # this (np rng) is used when [random_state=None]. Can also set directly random_state=79 
# shuffling is similar to stratification
kf = KFold(n_splits=5, shuffle=True, random_state=None) # shuffle= False by default, use cv=3 in next step
scores = cross_val_score(logreg, X, y, cv = kf) # cv=3 as good as cv = 5, prev. step not needed
print("Cross-validation scores: {}".format(scores))
print("Average cross-validation score: {:.2f} +/- {:.2f}".format(scores.mean(), scores.std()))

Cross-validation scores: [ 0.775  0.715  0.745  0.72   0.815]
Average cross-validation score: 0.75 +/- 0.04

In [17]:
# do a train test split at 70% training
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.7, stratify=y, random_state=0)

scalerS = StandardScaler()
#scalerM = MinMaxScaler()
scalerS.fit(X_train)
X_train = scalerS.transform(X_train)
X_test = scalerS.transform(X_test)

# define a logistic regression classifier with some initial values (set n_jobs to 1 if only one core)
#clf  = LogisticRegression(n_jobs=3,solver='liblinear')
clf = SVC(kernel='linear')
# define a paramter grid (dictionaries) of parameters to try
param_grid = {'C': [0.01, 0.1, 1, 10, 100],'max_iter': [100, 500, 1000, 5000]}

# define grid search with validation using 3 folds (stratified by default)
grid_search = GridSearchCV(clf, param_grid, cv=3)

# gridsearch is now a classifier with best parameters
grid_search.fit(X_train, y_train) # gridsearch finds best parameters & fits the whole train data, ready to predict

# print best parameters and best score
print("Best parameters: {}".format(grid_search.best_params_))
print("Best cross-validation score: {:.2f}".format(grid_search.best_score_))

# check test score
print("Test set score: {:.2f}".format(grid_search.score(X_test, y_test))) # score predicts first

E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=100).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=100).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=100).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=100).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=100).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=100).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=500).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=500).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=500).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=100).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=100).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=100).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=500).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=500).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=500).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=5000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=5000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=5000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=100).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=100).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=100).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=500).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=500).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=500).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=5000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=5000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)

E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=5000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=100).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=100).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=100).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=500).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=500).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=500).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=5000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=5000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=5000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)

Best parameters: {'max_iter': 500, 'C': 0.01}
Best cross-validation score: 0.74
Test set score: 0.76

E:\software\anaconda4\lib\site-packages\sklearn\svm\base.py:220: ConvergenceWarning: Solver terminated early (max_iter=500).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)

In [18]:
# predict values using optimized model
preds = grid_search.predict(X_test)

# print confusion matrix and performance on test set
print(confusion_matrix(y_test,preds))
print(classification_report(y_test,preds))
print("Best estimator:\n{}".format(grid_search.best_estimator_))

[[200  10]
 [ 61  29]]
             precision    recall  f1-score   support

          0       0.77      0.95      0.85       210
          1       0.74      0.32      0.45        90

avg / total       0.76      0.76      0.73       300

Best estimator:
SVC(C=0.01, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='linear',
  max_iter=500, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [19]:
SVC?

In [20]:
loans['default'].value_counts()

0    700
1    300
Name: default, dtype: int64

In [21]:
#----------------- try trees without processing

In [22]:
from sklearn.ensemble import RandomForestClassifier
loansT = pd.read_csv('loans.csv', header=0, sep = ',')
loansT["default"] = loansT["default"] -1
#loansT["history"] = loansT["credit_history"].apply(getHistory)
# not sure about existing_credits
dummy_columns2 = ['checking_balance','purpose','savings_balance','employment_length',
                 'installment_rate','other_debtors','residence_history', 'property','installment_plan',
                'housing','telephone','foreign_worker','job', 'personal_status']
new_loansT = pd.get_dummies(loansT, columns=dummy_columns2, drop_first=True)

new_loansT = new_loansT.drop(['credit_history'], axis=1)
new_loansT.head(5)

,months_loan_duration,amount,age,existing_credits,default,dependents,checking_balance_< 0 DM,checking_balance_> 200 DM,checking_balance_unknown,purpose_car (new),purpose_car (used),purpose_domestic appliances,purpose_education,purpose_furniture,purpose_others,purpose_radio/tv,purpose_repairs,purpose_retraining,savings_balance_501 - 1000 DM,savings_balance_< 100 DM,savings_balance_> 1000 DM,savings_balance_unknown,employment_length_1 - 4 yrs,employment_length_4 - 7 yrs,employment_length_> 7 yrs,employment_length_unemployed,installment_rate_2,installment_rate_3,installment_rate_4,other_debtors_guarantor,other_debtors_none,residence_history_2,residence_history_3,residence_history_4,property_other,property_real estate,property_unknown/none,installment_plan_none,installment_plan_stores,housing_own,housing_rent,telephone_yes,foreign_worker_yes,job_skilled employee,job_unemployed non-resident,job_unskilled resident,personal_status_female,personal_status_married male,personal_status_single male
0,6,1169,67,2,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,1,0,1,0,0,1,0,1,0,1,0,1,0,1,1,1,0,0,0,0,1
1,48,5951,22,1,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,0,1,0,0,0,1,1,0,0,0,1,0,1,0,1,0,0,1,1,0,0,1,0,0
2,12,2096,49,1,0,2,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,0,1,0,1,0,0,1,0,1,0,1,0,0,1,0,0,1,0,0,1
3,42,7882,45,1,0,2,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,1,0,0,0,0,1
4,24,4870,53,2,1,2,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,1,0,0,1,1,0,0,0,0,1,1,0,0,0,0,1

In [23]:
X = new_loansT.drop('default',axis=1)
y = new_loansT['default']
print(X.shape)
print(y.shape)
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.7, stratify=y, random_state=0)

param_grid2 = {'criterion':['gini','entropy'],'max_features': [7,24,48],'n_estimators': [10, 100, 1000]}
rfc = RandomForestClassifier(n_jobs=3)
# define grid search with validation using 3 folds (stratified by default)
kf = KFold(n_splits=5, shuffle=True, random_state=None)
clf2 = GridSearchCV(rfc, param_grid2, cv=kf)

# gridsearch is now a classifier with best parameters
clf2.fit(X_train, y_train)

# print best parameters and best score
print("Best parameters: {}".format(clf2.best_params_))
print("Best cross-validation score: {:.2f}".format(clf2.best_score_))

# check test score
print("Test set score: {:.2f}".format(clf2.score(X_test, y_test))) # score predicts first

(1000, 48)
(1000,)
Best parameters: {'n_estimators': 1000, 'criterion': 'entropy', 'max_features': 24}
Best cross-validation score: 0.75
Test set score: 0.75

In [24]:
preds2 = clf2.predict(X_test)

# print confusion matrix and performance on test set
print(confusion_matrix(y_test,preds2))
print(classification_report(y_test,preds2))
print("Best estimator:\n{}".format(clf2.best_estimator_))

[[192  18]
 [ 56  34]]
             precision    recall  f1-score   support

          0       0.77      0.91      0.84       210
          1       0.65      0.38      0.48        90

avg / total       0.74      0.75      0.73       300

Best estimator:
RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features=24, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=1000, n_jobs=3, oob_score=False,
            random_state=None, verbose=0, warm_start=False)

In [25]:
RandomForestClassifier?